
@server=https://084b9c81trial-dev-devtober-srv.cfapps.us10-001.hana.ondemand.com/
@service=/odata/v4/admin

####
GET {{server}}{{service}}/MaintenanceItem

####
POST {{server}}{{service}}/MaintenanceItem
Content-Type: application/json

{
    "problemDescription":"test"
}